---
- name: Ensure lead_controller is set and valid
  ansible.builtin.assert:
    that:
    - lead_controller is defined
    - lead_controller in groups.controllers
    msg: "lead_controller is either not defined or not found in the controller group"
  run_once: true

- name: Include supported vars
  ansible.builtin.include_vars: supported-values.yml

- name: Ensure valid CNI has been defined
  ansible.builtin.assert:
    that: cri in supported_cri
    msg: "{{ cri }} is not a supported CRI"
  run_once: true

- name: Ensure valid CNI has been defined
  ansible.builtin.assert:
    that: cni in supported_cni
    msg: "{{ cni }} is not a supported CNI"
  run_once: true

- name: Ensure vrrp_virtual_ip is valid
  ansible.builtin.assert:
    that: vrrp_virtual_ip | ansible.utils.ipaddr
    msg: "{{ vrrp_virtual_ip }} is not a valid IP address"
  run_once: true

- name: Ensure pod_subnet is valid
  ansible.builtin.assert:
    that: pod_subnet | ansible.utils.ipaddr
    msg: "{{ pod_subnet }} is not a valid subnet"
  run_once: true
