---

###
# Enable CRI plugin and set cgroup driver to systemd as per:
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
#

- name: Remove cri from disabled plugins list
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    line: disabled_plugins = ["cri"]

#- name: Set cri endpoints
#  ansible.builtin.command: crictl config --set runtime-endpoint=unix:///run/containerd/containerd.sock --set image-endpoint=unix:///run/containerd/containerd.sock

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

###
# Disable swap
#

- name: Remove swap ftsab entires
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: "^.*swap.*$"

- name: Disable swap
  ansible.builtin.command: swapoff -av
  register: swapoff
  failed_when: swapoff.stderr | length > 0
  changed_when: swapoff.stdout| length > 0

###
# Setup IP Tables as per:
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
#

- name: Set load peristence for br_netfilter and overlay modules
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/kubernetes.conf
    line: "{{ item }}"
    create: true
    owner: root
    group: root
    mode: "0644"
  with_items:
    - br_netfilter
    - overlay

- name: Ensure br_netfilter and overlay modules are loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Configure IP Tables
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

###
# Set node_ip
# Due to the bare metal requirements, we need to know the IP address of the NIC we are communicating with
# This can be set in different ways:
#   - Explicitly defining a role variable
#   - Setting ansible_host to a FQDN
#   - Setting ansible_host to a IP address
#
# node_ip is set depending in order of precedence:
#   - Explicity assigned
#   - ansible_host: FQDN
#   - ansible_host: IP address
#

- name: Set node_ip as a fact when explicity defined
  ansible.builtin.set_fact:
    node_ip: "{{ node_ip }}"
  when: node_ip is defined

- name: Resolve hostname, set node_ip set /etc/hosts
  when:
    - not ansible_host | ansible.utils.ipaddr
    - node_ip is not defined
  block:
    - name: Resolve IP when ansible_host is hostname
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.dig', '{{ ansible_host }}') }}"
      register: ipaddr

    - name: Set ip fact
      ansible.builtin.set_fact:
        node_ip: "{{ ipaddr.msg }}"

    - name: Make sure /etc/hosts exists
      ansible.builtin.file:
        path: /etc/hosts
        owner: root
        group: adm
        mode: "0644"
        state: file

    - name: Add /etc/hosts entires
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].node_ip }} {{ hostvars[item].ansible_host }}"
      with_items: "{{ groups.all }}"

- name: Set node_ip if ansible_host is an IP address and not explicitly defined
  ansible.builtin.set_fact:
    node_ip: "{{ ansible_host }}"
  when: node_ip is not defined
